### ISSUE TITLE
Azure DevOps is removing older build images 

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#116]
The Windows Server Core 1803 image is being removed on March 23, 2020. It must be removed or transition to another image as appropriate.

https://github.com/gaelcolas/Sampler/blob/d4e58e473a178e5eab98315de55d34a36b4d20ea/azure-pipelines.yml#L97

https://github.com/gaelcolas/Sampler/blob/d4e58e473a178e5eab98315de55d34a36b4d20ea/azure-pipelines.yml#L142

**Comment by tmeckel** [comment]
@johlju for not having to update the `vmImage`, would it be feasible to use `windows-latest`?
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

**Comment by gaelcolas** [comment]
If that works, yes. 
Although when a project uses win1803 for integration or unit test specifically, maybe we should notify the maintainer.

**Comment by johlju** [comment]
I have opened corresponding issues in all repos that I know have been converted. So fixing it here is important so we don't get more converted modules that is using this image. Agrre with @gaelcolas that if it works use '*-latest' for all images were possible, then we don't need to change this repo in the future. Each repo that is using the plaster template can change those images to something elese if they like.

**Comment by tmeckel** [comment]
Perhaps another way would be to add an option to the `Plaster` template that asks for the `vmImage` to use and which has a default value of `windows-latest` or `ubuntu-latest`.

**Comment by johlju** [comment]
Yep, that would work too.

**Comment by johlju** [comment]
This repo was updated to new build images.
