### ISSUE TITLE
Create a helper function to reduce code duplication

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#125]
https://github.com/gaelcolas/Sampler/blob/f688cfe33ed5edccbe967c95101b28d471460415/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L7-L18

**Comment by gaelcolas** [comment]
That'd be great.
Whoever tackle this, please make sure there's no precedence issue (`Sampler` must be loaded before the tasks using that function are imported), and make sure `build.ps1` does not depend on `Sampler`.
Reason is that `build.ps1` can be used to bootstrap something else than a module, and may be use with something else than `Sampler` (low coupling, high cohesion).

It is, however, tightly coupled with `Invoke-Build`, `powershell-yaml`, and `Resolve-Dependency.ps1` currently (but not an issue as long as we know about it).
