### ISSUE TITLE
Is the build task parameter `$BuiltModuleSubdirectory` needed? 

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#133]
Trying to document the build task parameters I found the out about the `$BuiltModuleSubdirectory` parameter. Looking at the build task parameters I see it suffixes the `OutputDirectory` when set.

I wonder in what scenario this is used, or if we can remove it. If there is a scenario when it should be used then external tasks need to use the `$BuildModuleOutput` parameter over the OutputParameter.

Was added here:
https://github.com/gaelcolas/Sampler/commit/8a867a45485ad0c7a16e33eb887480fec843943d

**Comment by johlju** [comment]
From @gaelcolas in offline discussion:
"... that's to allow building the module under another subfolder instead than just under Output/. The reason is to avoid the Get-DscResource to see same module/resources twice. I'd leave that in, as I'm not convinced the current way we do it will always play nicely."

**Comment by stevehose** [comment]
I have a project that uses Sampler along with a host of other DSC resources. When I use /modules as the $BuildModuleSubdirectory, I can avoid duplicate imports. Otherwise, I get duplicates. This variable/parameter is very much needed.
