### ISSUE TITLE
Move Plaster template source files to .template files or a better folder

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#135]
We need to change move the Plaster template files into .template files (or at least to another folder where the Plaster template source files exist). This is needed to be able to move the module to a better folder and file structure pattern (private/public pattern) (tracked in issue #134), and also to be able to make tests for the Sampler module code.

**Comment by gaelcolas** [comment]
I'd argue that if we have functions in private/public folder, we don't need `Get-Something` and `Get-PrivateFunction` at all.
The only reason they were there is because I wanted to show some basic example.

Turns out I've learnt that when you create a template with those commands, people forget to remove them, and then gets into trouble with 2 modules having the same public command (`Get-Something`) and need to use `-AllowClobber on install...

Lesson learnt: templates should not copy those files for example, like we're doing in the `dsccommmunity` or `SimpleModule` module types of the template.

That said, having a way to template the functions (a bit like a snippet), could be a good idea.
We could add that under another folder under `Sampler/Sampler/Templates/`

**Comment by johlju** [comment]
I think we should template all so that the pipeline files in root of Sampler is just for Sampler's own build pipeline (that dogfood itself) and not used by any Plaster template. That way it might be more clear that the entire repository is not the template (which the name of the project can suggest).

**Comment by johlju** [comment]
> templates should not copy those files for example, like we're doing in the dsccommmunity or SimpleModule module types of the template.

I think we should copy the files, but we could comment the code in them so they are not exported when building? 🤔 I think there is a value by copying them in the template so new users unfamiliar with the pattern easily understands it. It should be possible to make a custom module where they can be excluded for more experienced users.

**Comment by gaelcolas** [comment]
> I think we should template all so that the pipeline files in root of Sampler is just for Sampler's own build pipeline (that dogfood itself) and not used by any Plaster template.

Hmmmm, I'm not 100% sure that's a good idea yet.

I mean, the Integration tests would need to be pretty solid, which means:
- validating build.ps1 & Build.yaml features
- validating ResolveDependency
- validating other features such as gitignore, gitversion, azure-pipelines

So I'm ok to move out progressively as the Integration tests validate this stuff.
In the meantime, having them in use when building Sampler is integration testing by dogfooding (not great, but better than nothing).

I'm afraid that while we build up Integration testing, we miss to edit the files if they live in two locations (for Sampler and for template).

**Comment by johlju** [comment]
I understand your concern, but there are already several aspects in the templates that are not and cannot be dogfood:ed with Sampler. There is also a catch 22 in this repo that prevents testing stuff. We was able to add integration tests because there was no template currently using the folder `/test/integration`. 

To be able to start (unit) testing this module we need to 

- move all files in `/tests` that is part of the templates to assets.

To be able to split the modules functions into private/public pattern we need to

- move all files in source folder (`Sampler´) that is part of the templates to assets.

After the above is done we can start adding unit tests to functions and build tasks to test current functionality. 

We then can try to move functions into the private/public pattern and start testing those functions appropriately, I saw issues with this in DocGenerator where build tasks could not use private functions, so we'll see how well that goes.

After all that we can look at properly integration tests different aspects of the built module (integration tests different aspects of the templates). But that is way in the future.

My thoughts. 😄

**Comment by gaelcolas** [comment]
I think this is mostly done, except the entries in `Templates/Sampler/plasterManifest.xml` that refer to anything under `Sampler/` for source.
I think most of them points to `Sampler/Assets` anyway, so should be able to be moved by "just" moving under `Templates/Sampler/` and updating the XML.
