### ISSUE TITLE
The function Get-ModuleVersion should handle corrupt GitVersion

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#157]
There is an issue with `gitversion` where it can stop working unless the dotnet bundle extract temp variable is specified. When that happens `gitversion` becomes corrupt and fails.
This should be handled by making sure `gitversion` returns the correct value, otherwise it should fall-back for example to use module manifest or just use a dummy version number like `0.0.1`.
But at minimum it should fail with a correct error message so it is easy to understand why the build failed.

https://github.com/gaelcolas/Sampler/blob/5ecc9abe8be9d36a0b72c7237493f0fa5b204070/.build/tasks/Common.Functions.psm1#L96-L101

**Comment by gaelcolas** [comment]
I believe GitVersion has been fixd (actually .Net core).
Have you experienced this recently? (I have not)

**Comment by johlju** [comment]
Honestly I always set this paramete rnow jsut because it works for a while then break and it is annoying. So if we are confident that this always work for now then we can close this issue.

**Comment by gaelcolas** [comment]
Sounds good. Can always re-open later.
