### ISSUE TITLE
WARNING: The module manifest 'Datum.InvokeCommand.psm1' could not be processed because it is not a valid PowerShell module manifest file.

### ISSUE THREAD

**Issue by raandree** [gaelcolas/Sampler#181]
The project https://github.com/raandree/Datum.InvokeCommand builds fine locally except from #97. However, in Azure Pipelines I get this and have no clue how to troubleshoot this:

```
Importing tasks from module DscResource.DocGenerator
	 Loading Task.Generate_Conceptual_Help...
	 Loading Task.Generate_Wiki_Content...
	 Loading Task.Publish_GitHub_Wiki_Content...
WARNING: The module manifest 'Datum.InvokeCommand.psm1' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: /home/vsts/work/1/s/source/Datum.InvokeCommand.psd1
Could not load tasks for module DscResource.DocGenerator.
ERROR: Missing property 'ProjectName'.
WARNING: The module manifest 'Datum.InvokeCommand.psm1' could not be processed because it is not a valid PowerShell module manifest file. Remove the elements that are not permitted: /home/vsts/work/1/s/source/Datum.InvokeCommand.psd1 File: /home/vsts/work/1/s/build.ps1.
Build ABORTED /home/vsts/work/1/s/build.ps1. 0 tasks, 1 errors, 1 warnings 00:00:01.1535477
```

As we all know the psm1 is not the module manifest and there is not a single psm1 file in the repo. Any idea what's wrong?

**BTW, besides this using the Sampler is really easy and you get a ton of features and checks!**

**Comment by johlju** [comment]
@raandree is this still an issue?

**Comment by gaelcolas** [comment]
From a quick glance, it sounds like the `Build.psd1` for `ModuleBuilder` is "missing" from the source folder.
You should create it and add:
```PowerShell
@{
    SourcePath = './Datum.InvokeCommand.psd1'
}
```

Needing this is a known issues with ModuleBuilder referenced here: https://github.com/PoshCode/ModuleBuilder/issues/94

Reopen if that's not solving your issue @raandree and ping me on Teams.
