### ISSUE TITLE
Build step throws an error

### ISSUE THREAD

**Issue by ykuijs** [gaelcolas/Sampler#192]
#### Details of the scenario you tried and the problem that is occurring
Today I noticed that v0.106.0 and 0.106.1 throw an error when building a module:
```
Building Module to C:\src\SChannelDsc\output\SChannelDsc...
ERROR: Cannot find path 'C:\src\SChannelDsc\output\SChannelDsc\0.0.1\C:\src\SChannelDsc\output\SChannelDsc\0.0.1\SChannelDsc.psd1' because it does not exist.
At C:\src\SChannelDsc\output\RequiredModules\Sampler\0.106.1\tasks\Build-Module.ModuleBuilder.build.ps1:134 char:33
+         $RootModuleDefinition = Get-Content -Raw -Path $Psm1Path
+                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\src\SChannelDsc\output\RequiredModules\Sampler\0.106.1\tasks\Build-Module.ModuleBuilder.build.ps1:39 char:1
+ Task Build_Module_ModuleBuilder {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\src\SChannelDsc\build.ps1:211 char:13
+             task $Workflow $WorkflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 3 tasks, 1 errors, 0 warnings 00:00:00.9374501
```

The code tries to load the psd1 file from an incorrect location:
C:\src\SChannelDsc\output\SChannelDsc\0.0.1\**C:\src\SChannelDsc\output\SChannelDsc\0.0.1\SChannelDsc.psd1**

This issue occurs in the following file on line 134:
https://github.com/gaelcolas/Sampler/blob/90eb46a239b60d8e6d41f819aa4d2ccef9473ffa/.build/tasks/Build-Module.ModuleBuilder.build.ps1#L128-L136

#### Suggested solution to the issue
The in the above code on line 133, Join-Path is creating a new path. However $BuildModule.RootModule is already the full path, which is now concatenated to another path, resulting in the double path and in the end the error.

Not sure why this Join-Path is added, but either file the file name should be extracted or the Join-Path can be removed altogether since the RootModule property already contains the path.

#### The operating system the target node is running
Win10 2004 (May 2020)

#### Version and build of PowerShell the target node is running
PS5.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
0.106.0 and v.106.1, where the above code was added.

**Comment by gaelcolas** [comment]
Had a closer look and it seems that your project
- uses an old version of ModuleBuilder (you have the v1.0.0) pinned
- should pin pester to 4.10.1 (you are on `latest`)

**Comment by gaelcolas** [comment]
that said, it does not seem to be the root cause, as even with those fixed, it's still an issue. Weird.

**Comment by gaelcolas** [comment]
v0.107.1 (released in around 10 min) should fix this. Let me know if that's still an issue.

**Comment by ykuijs** [comment]
Great, will test that version later today.

**Comment by gaelcolas** [comment]
as discussed offline, you also need to update the `Build.yml` with `CopyPaths:` instead of `CopyDirectories:`, that parameter name has changed since ModuleBuilder 1.0.0.
