### ISSUE TITLE
Updating existing resource with custom "source" folder throws an error 

### ISSUE THREAD

**Issue by ykuijs** [gaelcolas/Sampler#218]
#### Details of the scenario you tried and the problem that is occurring
When I try to update my DSC module with new versions of the scripts, I receive an error message. I am using the module name (SharePointDsc) as the name for the source folder (instead of "source" which is used in other DSC modules).

I used the following code:
```PowerShell
$samplerModule = Import-Module -Name Sampler -PassThru
$invokePlasterParameters = @{
  TemplatePath    = Join-Path -Path $samplerModule.ModuleBase -ChildPath 'Templates/Sampler'
  DestinationPath = '..\'
  ModuleType      = 'dsccommunity'
  ModuleName      = Split-path -Leaf $PWD
  SourceDirectory = 'Source'
}
Invoke-Plaster @invokePlasterParameters
```

#### Verbose logs showing the problem
The following error is thrown. Looks like the variable ${PLASTER_PARAM_ModuleName} isn't resolved properly:
```PowerShell
Invoke-Plaster : Cannot validate argument on parameter 'SourceDirectory'. The argument "SharePointDsc" does not belong to the set "${PLASTER_PARAM_ModuleName},source,src" specified 
by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:9 char:16
+ Invoke-Plaster @invokePlasterParameters
+                ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Plaster], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-Plaster

```

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running

OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 2009
WindowsBuildLabEx    : 19041.1.amd64fre.vb_release.191206-1406
OsLanguage           : en-US
OsMuiLanguages       : {en-US, en-GB}

#### Version and build of PowerShell the target node is running

Name                           Value                                                                                                                                                  
----                           -----                                                                                                                                                  
PSVersion                      5.1.19041.610                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                
BuildVersion                   10.0.19041.610                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                        
WSManStackVersion              3.0                                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                                    
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
v0.109

**Comment by gaelcolas** [comment]
I think that's specific to the DSC Community template, because we expect it to be always `source` (decided after you started the migration iirc).

Anyway the way to fix this is to create a plaster manifest in Templates/Build, so that we can use the command `Add-Sample -Sample Build` instead of the "full" Sampler template.

**Comment by gaelcolas** [comment]
Hey @ykuijs, since a lot of things have changed in Sampler, including how we resolve the "source" folder regardless of its name, could you test with the latest version? (fresh clone + `-ResolveDependency`)

**Comment by gaelcolas** [comment]
Please re-open if it's still an issue.
