### ISSUE TITLE
Wrong resource name is added to module manifest property DscResourcesToExport

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#220]
For MOF resources the friendly name should be added to the module manifest property DscResourcesToExport. Currently the name is added making the wrong resource name to be added. For the module SqlServerDsc that means the resorce names are wrongly prefixed with DSC or MSFT.

```
DscResourcesToExport = @(...,'DSC_SqlAG',...,'MSFT_SqlDatabaseOwner',...)
```

The code that makes this happen was added in PR #214.

https://github.com/gaelcolas/Sampler/blob/7641afced95dc93ef2d701aa82997b5e181e1efa/.build/tasks/Common.Functions.psm1#L728

The exported names should look like this.

```
DscResourcesToExport = @(...,'SqlAG',...,'SqlDatabaseOwner',...)
```

An example MOF

```
[ClassVersion("1.0.0.0"), FriendlyName("SqlAG")]
class DSC_SqlAG : OMI_BaseResource
{
    ...
};
```

**Comment by johlju** [comment]
@NicolasBn saw that you built the task and might have it fresh in your mind. Do you have bandwidth to look into this issue? Otherwise no worries, I can do it in a couple of weeks.

**Comment by NicolasBn** [comment]
@johlju I will work on it this week.

**Comment by NicolasBn** [comment]
Faster than expected @johlju !

I tested on SqlDscResource, that's the result : 
`DscResourcesToExport = @('SqlAG','SqlAGDatabase','SqlAgentAlert','SqlAgentFailsafe','SqlAgentOperator','DSC_SqlAGListener','SqlAGReplica','SqlAlias','SqlAlwaysOnService','SqlConfiguration','SqlDatabase','SqlDatabaseDefaultLocation','SqlDatabaseMail','SqlDatabaseObjectPermission','SqlDatabasePermission','SqlDatabaseRole','SqlDatabaseUser','SqlEndpoint','DSC_SqlEndpointPermission','SqlLogin','SqlMaxDop','SqlMemory','SqlPermission','SqlProtocol','SqlProtocolTcpIp','SqlReplication','SqlRole','SqlRS','SqlRSSetup','SqlScript','SqlScriptQuery','DSC_SqlSecureConnection','SqlServiceAccount','SqlSetup','SqlTraceFlag','SqlWaitForAG','SqlWindowsFirewall','SqlDatabaseOwner','SqlDatabaseRecoveryModel','SqlServerEndpointState','SqlServerNetwork')`

**Comment by johlju** [comment]
Looks good! I will review the PR. Thank you!

**Comment by gaelcolas** [comment]
Can this be closed @johlju ?
Looks like the pr is merged.

**Comment by johlju** [comment]
Yes, I think it can. Pretty sure it was fixed.
