### ISSUE TITLE
Update .gitattributes template to include DLL

### ISSUE THREAD

**Issue by ykuijs** [gaelcolas/Sampler#222]
#### Details of the scenario you tried and the problem that is occurring
Please update the .gitattributes template for DscResources to include *.dll as binary as well. Right now this is causing issues with SPDsc where precompiled DLLs are changed during cloning of the repo.

#### Suggested solution to the issue
Add the following line to .gitattributes:
```
*.dll binary
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
dev

**Comment by gaelcolas** [comment]
fixed in latest release: https://github.com/gaelcolas/Sampler/blob/master/Sampler/Templates/Git/gitattributes#L14
