### ISSUE TITLE
Correctly support Pester 5 code coverage

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#223]
We should add these settings to make sure the pipeline can generate the code coverage and test result file. The test task `Invoke_Pester_Tests` (`Invoke-Pester.pester.build.ps1`) need to be refactored starting after:

https://github.com/gaelcolas/Sampler/blob/cdb6e17382d7c3d866759e3ff52a586f29646c60/.build/tasks/Invoke-Pester.pester.build.ps1#L91

The configuration block for Pester 5.x are totally different than Pester 4.x. The the properties that are needed are below. Values must of course be changed on some to use configurable values, but this gives the gist of it.

```powershell
# Start from the default configuration values.
$pesterConfig = [PesterConfiguration]::Default

# Output similar to Pester 4.10.1
$pesterConfig.Output.Verbosity = 'Detailed'

# The path to one or more test files.
$pesterConfig.Run.Path = @(
    '.\tests\Unit\SqlServerDsc.Common.Tests.ps1'
)

# Exit after test has run complete.
$pesterConfig.Run.Exit = $true

# If Invoke-Pester should return an object for further processing.
$pesterConfig.Run.PassThru = $true

# Only run these tags.
$pesterConfig.Filter.Tag = @(
    'GetRegistryPropertyValue'
    'FormatPath'
    'ConnectUncPath'
)

# Generate the JaCoCo file 'coverage.xml' in /output.
$pesterConfig.CodeCoverage.Enabled = $true
$pesterConfig.CodeCoverage.OutputFormat = 'JaCoCo'
$pesterConfig.CodeCoverage.OutputPath = './output/coverage.xml'
$pesterConfig.CodeCoverage.OutputEncoding = 'UTF8'
$pesterConfig.CodeCoverage.Path = '.\source\Modules\SqlServerDsc.Common\SqlServerDsc.Common.psm1'
$pesterConfig.CodeCoverage.ExcludeTests = $true # Exclude our own test code from code coverage.

# Generate the NUNit 2.5 file 'testResults.xml' in /output
$pesterConfig.TestResult.Enabled = $true
$pesterConfig.TestResult.OutputFormat = 'NUnit2.5'
$pesterConfig.TestResult.OutputPath = './output/testResults.xml'
$pesterConfig.TestResult.OutputEncoding = 'UTF8'
$pesterConfig.TestResult.TestSuiteName = 'Pester5' # Can be set to any name, preferably the module name?

Invoke-Pester -Configuration $pesterConfig
```

**Comment by johlju** [comment]
@NicolasBn I added an issue if you have time to work on it. Ping me if you have any issues. There aren't a repo yet to test this on. But the branch here will run tests correctly for `'.\tests\Unit\SqlServerDsc.Common.Tests.ps1'`: https://github.com/johlju/SqlServerDsc/tree/f/support-pester-5

**Comment by johlju** [comment]
The above branch now contain a unit test for SqlProtocol that has been converted to Pester 5. So if we want something to test on we could strip out all other resource and tests from a working branch. Just keep the _SqlProtocol_ resource, the module _SqlServerDsc.Common_, and the unit tests for both.

**Comment by NicolasBn** [comment]
I just have one question. Why we don't use the sames parameters than pester 4 ( example : -CodeCoverageOutputFile) ?

**Comment by johlju** [comment]
They does not exist in Pester 5. Some parameters was added as legacy parameter set so not to break execution icy Invoke-Pester in pipelines, but they does not do anything.

**Comment by johlju** [comment]
Correction, they do work looking at the code https://github.com/pester/Pester/blob/v5.0/src/Pester.ps1. But they are deprecated so we shouldn't use them when we update our pipeline.

**Comment by NicolasBn** [comment]
Understood ! I will work on this !

**Comment by NicolasBn** [comment]
I inspected the task and I don't have a clear idea how to implement pester 5 support. 
In [this](https://github.com/gaelcolas/Sampler/blob/e5de6584dc01347ba908e7d4ce23cf868c9db9f2/.build/tasks/Invoke-Pester.pester.build.ps1#L117-L167) part of code, the task is based on the parameters names of Invoke-Pester and the values in build.yaml. 
But with Pester5, we only use the `-Configuration` parameter with `[PesterConfiguration]` class. And you said the other parameters are deprecated. Is it possibility that they will be removed in the future version of Pester ? I think yes, and it's not very efficient to base the task on it. 

I look at to split the task of two parts (Pester4 / Pester5) and add another common function.
But if you have another approach/idea... :)

**Comment by johlju** [comment]
The task need to make use of `if ($isPester5)` in various places and do different things depending on Pester version. That part you linked to can only run for Pester 4. Is it easier to make two tasks, one that runs if Pester version is less than 5 and the other one runs if the Pester version is 5 or higher?

**Comment by johlju** [comment]
Did you mean something like this? I'm good with that. Common code could be in common functions.

```
task Invoke_Pester_Tests_v4 -if ((Get-Module -Name 'Pester').Version -lt '5.0.0') {
    # Code for Pester 4
}

task Invoke_Pester_Tests_v5 -if ((Get-Module -Name 'Pester').Version -ge '5.0.0') {
    # Code for Pester 5
}

Task Invoke_Pester_Tests Invoke_Pester_Tests_v4, Invoke_Pester_Tests_v5
```

**Comment by NicolasBn** [comment]
I ignored the existence of -if parameter in 'task'. Indeed, that'll facilitate the writing. 
I just thought to have one task with big if (I don't really like this :) ) :
```
if ((Get-Module -Name 'Pester').Version -lt '5.0.0'){
# pester 4
}
else
{
# pester 5
}
```

Your approach sounds better.

**Comment by johlju** [comment]
Your suggestion might work better if you can’t import Peater into the session in that task `-if`  evaluation. Today Pester is not imported until the import inside the current task. 

Use the best option :)

**Comment by johlju** [comment]
Hmm.. prior to running v4 and v5 task as I mentioned above there could be another task `Import_Pester` first that imports Pester into the session. 🤔

**Comment by NicolasBn** [comment]
I tested to place `Import-Module -Name 'Pester' -MinimumVersion 4.0 -ErrorAction Stop` on top of `Invoke-Pester.pester.build.ps1`, just after `Import-Module -Name "$PSScriptRoot/Common.Functions.psm1"`

The module was correctly imported. But if it's not present, the entirely build task failed not just Pester task because sampler doesn't find any Pester module. 

But after somes thinking... What do you say about that :
```
task Invoke_Pester_Tests_v4 -if ( ( (Get-Module -List Pester).Version | Where-Object -FilterScript { $_-ge [system.version]'4.0.0'} ) -lt [system.version]'5.0.0') {
    # Code for Pester 4
}

task Invoke_Pester_Tests_v5 -if ((Get-Module -List Pester).Version -ge [system.version]'5.0.0') {
    # Code for Pester 5
}

Task Invoke_Pester_Tests Invoke_Pester_Tests_v4, Invoke_Pester_Tests_v5
```

I added a Where-Object for Pester 4 task because we don't want to use version 3.* of pester. 

This is the result if no pester module is present : 
```
Task /./test/Pester_Tests_Stop_On_Fail/Invoke_Pester_Tests skipped.
Task /./test/Pester_Tests_Stop_On_Fail/Upload_Test_Results_To_AppVeyor skipped.
```

And the error : 
![image](https://user-images.githubusercontent.com/25097989/103371143-ffc8cc00-4ace-11eb-81d5-72e8e50990db.png)

**Comment by johlju** [comment]
The problem I can see with using `-ListAvailable` is that if the wrong version of Pester exist somewhere in a module folder on the users computer. 🤔 What if Pester 4 should be used for the repo but the user have Pester 5 installed in a module folder outside of the repo, then that will be found by `-ListAvailable`?

Using the following I thought would mitigate that? Or will the same happen as above?

```
task Import_Pester {
    # This will import the Pester version in the first module folder it finds which will be '/output/RequiredModules'?
    Import-Module -Name 'Pester' -MinimumVersion 4.0 -ErrorAction Stop
}

# This will evaluate the module version already imported into the session.
task Invoke_Pester_Tests_v4 -if ((Get-Module -Name 'Pester').Version | Where-Object -FilterScript { $_-ge [System.Version] '4.0.0' -and $_ -lt [System.Version] '5.0.0' }) {
    # Code for Pester 4
}

# This will evaluate the module version already imported into the session.
task Invoke_Pester_Tests_v5 -if ((Get-Module -Name 'Pester').Version -ge '5.0.0') {
    # Code for Pester 5
}

Task Invoke_Pester_Tests Import_Pester, Invoke_Pester_Tests_v4, Invoke_Pester_Tests_v5
```

**Comment by NicolasBn** [comment]
Indeed, with `ListAvailable` we get all the version of Pester present in the system. I can add a clause to the `Where-Object` to filter on the module path. 

Apparently, the `-if` parameter needs a boolean value. We should force the type : 
`[System.Boolean]((Get-Module -Name 'Pester').Version | Where-Object -FilterScript { $_-ge [System.Version] '4.0.0' -and $_ -lt [System.Version] '5.0.0' })`

**Comment by johlju** [comment]
Sounds good if it works 😊

**Comment by NicolasBn** [comment]
@johlju I tried to solve this issue based on our last conversation. But I'm encoutering a strange comportment with first execution of test tasks. 
![image](https://user-images.githubusercontent.com/25097989/107485785-879cfe00-6b84-11eb-9078-c769473fc0e5.png)

All the pester tasks are skip when I have v5 of pester.
But the pester module is correctly imported : 

![image](https://user-images.githubusercontent.com/25097989/107485968-c5018b80-6b84-11eb-8e02-329dbf2dfba8.png)

And when I start a second execution of tests : 

![image](https://user-images.githubusercontent.com/25097989/107486121-ef534900-6b84-11eb-8e89-aad4d587fa6f.png)

The pester module is correctly detected, and the `Invoke_Pester_Tests_v5` task run.

**Comment by johlju** [comment]
@NicolasBn can you see if you the change to `Invoke-Pester.pester.build.ps1 ` helps see the PR I sent in this morning https://github.com/gaelcolas/Sampler/pulls. If not, have you pushed a working branch somewhere that I can clone to see what is going on?

**Comment by johlju** [comment]
@NicolasBn when the PR I linked to above is merged then I can merge a PR in FileSystemDsc that will fully work with Pester 5 in the main branch. So that would be a simple repo to clone an work with. I let you know when it is available.

**Comment by NicolasBn** [comment]
I read your PR, but I think that's problem come from an execution scope. The execution of `-If` parameter might be before the execution of `Import_Pester` task.

**Comment by johlju** [comment]
I take a look and try to reproduce, but will be tomorrow.

**Comment by johlju** [comment]
Need to push this to Friday (tomorrow) - to much at the day job. 🙂 Still on the todo.

**Comment by johlju** [comment]
@NicolasBn The issue is that the `-If` parameter takes a scriptblock, so it was evaluated wrong. Same issue on the _Pester 4_ evaluation.

Changing to this fixes it.

```
task Invoke_Pester_Tests_v5 -If {[System.Boolean] ((Get-Module -Name 'Pester').Version -gt [System.Version]'5.0.0')} {
```

Notice the added braces in the above line - written out a bit it looks like this:

```
{
    [System.Boolean]((Get-Module -Name 'Pester').Version -gt [System.Version]'5.0.0')
}
```

**Comment by NicolasBn** [comment]
Thank you @johlju  ! Indeed, that works well ! Do you have any comments to the rest of code ?
I tried to conserve the historic features with the different sources of data (build.yaml/parameter/etc.).

**Comment by johlju** [comment]
After a quick glance I think code coverage should not be a default, instead only be used if configured through build.yaml so that a repo can turn it off if the repo wants to. 🤔 
Let me know when you send in a PR, I can tests and review then.

**Comment by johlju** [comment]
@NicolasBn I just merged a PR in the repo FileSystemDsc to support Pester 5. So this repo is now using Pester 5 for all tests. It just waits for the PR so it can get the code coverage working again. 🙂 So if you need a simple repository to test your code changes then use this https://github.com/dsccommunity/FileSystemDsc.
