### ISSUE TITLE
DSC Plaster Template: add question for name of Main branch

### ISSUE THREAD

**Issue by PlagueHO** [gaelcolas/Sampler#225]
To support change to `main` branch name, plaster template could be updated to ask what the name of the main branch is. It should probably default to `main` now, but if `master` is specified then certain settings would be removed.

**Comment by johlju** [comment]
See the blog post https://dsccommunity.org/blog/convert-master-to-main/ for the places that the Plaster template 'dsccommunity' (plus others) need to change the default branch name (or add properties to support it).

**Comment by gaelcolas** [comment]
fixed (and new default) in latest release.
