### ISSUE TITLE
Autogeneration of CHANGELOG.md

### ISSUE THREAD

**Issue by GitMje** [gaelcolas/Sampler#227]
This is a question/suggestion.  Updating the CHANGELOG.md seems like redundant work once a person has created a well formatted commit message.  Question: **Is there a reason to not autogenerate the CHANGELOG?** (other than the time/effort of doing so)?  If not, I suggest autogenerating it.  I can tell you as a new contributor adding a few simple Readme changes, it creates friction to contributing.

The CI gate for ensuring that the author has updated the CHANGELOG is clever (nice idea on this).  It could be converted into/replaced by a step to run a autogenerator instead to remove work from the author.  If the current reason to manually update the CHANGELOG is that the commit messages are of poor quality, it seems that the commit message quality would be the issue for which to solve.  A quality gate on the commit messages would fix that issue.

I suspect that you may be aware of these tools, but [npm has a nice package for CHANGELOG generation](https://www.npmjs.com/package/auto-changelog) and there are cool tricks to [format the changelog structure](https://www.mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/).

I can look into how to do it, if you agree it is useful.

**Comment by johlju** [comment]
I thought many times that generating this automatically would be great, especially for minor changes. But I'm afraid the commit messages from contributors are normally not that descriptive so they fit in the change log (which is also the release notes in the module manifest and PowerShell Gallery). If it would generate automatically and the commit message are not informative enough the contributor need to use git-fu to reword the commit messages before a merge could happen. Also any misspellings will be hard to fix once the PR are merged as the main branch need to be "reworded". 

Honestly I think there will be a bigger pain handling rewording of commit messages than changing the CHANGELOG.md manually. 🤔 

@gaelcolas what are your thoughts around this?

**Comment by GitMje** [comment]
@johlju one thought is to use a [precommit spellcheck hook](https://github.com/mprpic/git-spell-check).  Precommit hooks are tricky to enforce to cloned repos, but it can be done.
