### ISSUE TITLE
Add SECURITY.MD to DSC Plaster Template

### ISSUE THREAD

**Issue by PlagueHO** [gaelcolas/Sampler#229]
It is GitHub security best practice to include a SECURITY.MD file documenting security policy for the project.

Here are a few common topics that are documented in a security policy:

Supported versions
How to responsibly report a security vulnerability
Security related configuration
Known security gaps and future enhancements

@johlju, @gaelcolas - There could be resource specific content and security info, but also links to things like DSC security best practices (e.g. MOF encryption).

**Comment by PlagueHO** [comment]
Here is standard content GitHub adds when creating a SECURITY.MD for you:
```text
# Security Policy

## Supported Versions

Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |

## Reporting a Vulnerability

Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.
```

**Comment by johlju** [comment]
I looked into this before but thought it was more focused on reporting vulnerabilities, and the supported version would always be the latest (preview) which equals the code in the default branch, so thought that was not relevant either.  Using it to link to  DSC security best practices could be good. Maybe add a default text around that? For example SqlServerDsc is using underlaying SMO and other PowerShell that is not supported by the DSC Community. Also what is "supported" in the sense of OSS in the DSC Community? 🙂 

@PlagueHO maybe you can put together a default text for us to build on? 🤔

**Comment by gaelcolas** [comment]
Added in latest release, feel free to open issues or PR to update the SECURITY.md template.
