### ISSUE TITLE
Create_changelog_release_output broken in 0.109.9

### ISSUE THREAD

**Issue by hackjammer** [gaelcolas/Sampler#261]
#### Details of the scenario you tried and the problem that is occurring
Create_changelog_release_output fails as it tries to ```[System.IO.File]::WriteAllLines``` (line 140) on a path ```$BuiltModuleManifest``` that contains a * glob character (which appears to be coming from the default $ModuleVersion value in Get-SamplerBuiltModuleManifest called at line 63).

#### Verbose logs showing the problem
```powershell
===============================================================================
                        CREATE CHANGELOG RELEASE OUTPUT
Create ReleaseNotes from changelog and update the Changelog for release
-------------------------------------------------------------------------------
  /./build/Create_changelog_release_output
  C:user\ModuleName\output\RequiredModules\Sampler\0.109.9\tasks\release.module.build.ps1:41

        OutputDirectory       = 'C:user\ModuleName\output'
        ReleaseNotesPath      = 'C:user\ModuleName\output\ReleaseNotes.md'
        ChangeLogOutputPath   = 'C:user\ModuleName\output\CHANGELOG.md'
        Built Module Manifest = 'C:user\ModuleName\output\ModuleName\*\ModuleName.psd1'
        Module Version        = '0.1.0'
        Module Version Folder = '0.1.0'
        Pre-release Tag       = ''
VERBOSE: Loading module from path 'C:user\ModuleName\output\RequiredModules\ChangelogManagement\2.1.4\ChangelogManagement.psd1'.
VERBOSE: Importing function 'Add-ChangelogData'.
VERBOSE: Importing function 'ConvertFrom-Changelog'.
VERBOSE: Importing function 'Get-ChangelogData'.
VERBOSE: Importing function 'New-Changelog'.
VERBOSE: Importing function 'Update-Changelog'.
VERBOSE: Loading module from path 'C:user\ModuleName\output\RequiredModules\Configuration\1.3.1\Configuration.psd1'.
VERBOSE: Importing function 'Add-MetadataConverter'.
VERBOSE: Importing function 'ConvertFrom-Metadata'.
VERBOSE: Importing function 'ConvertTo-Metadata'.
VERBOSE: Importing function 'Export-Configuration'.
VERBOSE: Importing function 'Export-Metadata'.
VERBOSE: Importing function 'Get-ConfigurationPath'.
VERBOSE: Importing function 'Get-Metadata'.
VERBOSE: Importing function 'Import-Configuration'.
VERBOSE: Importing function 'Import-Metadata'.
VERBOSE: Importing function 'InitializeStoragePaths'.
VERBOSE: Importing function 'ParameterBinder'.
VERBOSE: Importing function 'Test-PSVersion'.
VERBOSE: Importing function 'Update-Metadata'.
VERBOSE: Importing function 'Update-Object'.
VERBOSE: Importing alias 'Get-ManifestValue'.
VERBOSE: Importing alias 'Get-StoragePath'.
VERBOSE: Importing alias 'Update-Manifest'.
Built Manifest C:user\ModuleName\output\ModuleName\*\ModuleName.psd1
ERROR: Exception calling "WriteAllLines" with "3" argument(s): "Illegal characters in path."
At C:user\ModuleName\output\RequiredModules\Sampler\0.109.9\tasks\release.module.build.ps1:140 char:13
+             [System.IO.File]::WriteAllLines($BuiltModuleManifest, $Ma ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:user\ModuleName\output\RequiredModules\Sampler\0.109.9\tasks\release.module.build.ps1:41 char:1
+ task Create_changelog_release_output {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:user\ModuleName\build.ps1:215 char:13
+             task $Workflow $WorkflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:user\ModuleName\build.ps1:215 char:13
+             task $Workflow $WorkflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 8 tasks, 1 errors, 0 warnings 00:00:36.0581970
Exception calling "WriteAllLines" with "3" argument(s): "Illegal characters in path."
At C:user\ModuleName\output\RequiredModules\Sampler\0.109.9\tasks\release.module.build.ps1:140 char:13
+             [System.IO.File]::WriteAllLines($BuiltModuleManifest, $Ma ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ArgumentException

    ```

#### Suggested solution to the issue
Keep $ModuleVersion in this task?

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
N/A

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1909
WindowsBuildLabEx    : 18362.1.amd64fre.19h1_release.190318-1202
OsLanguage           : en-US
OsMuiLanguages       : {en-US}
-->

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
N/A

**Comment by hackjammer** [comment]
I see this has actually been fixed on master... https://github.com/gaelcolas/Sampler/commit/e7a6bdcbaa13f8c86c346c339dca06a337672135#diff-9b7eae0ce78a8b06c5c84aef90c5a2524b4fdc365d98a5084dc4bdba8ac94dce

Problem is, this was a breaking change that was released, and it looks like your CI was broken for 0.109.9 - how can we prevent this in future? Do you recommend pinning Sampler version?

**Comment by johlju** [comment]
Normally it best to pin a version that works so the pipeline does not break, and move to a new version if new functionality is needed. Build 0.109.10 was released so hopefully this is resolved for you now?

**Comment by johlju** [comment]
0.110.0 was released now. Closing this issue, pleas reopen if this should be discussed further. 🙂
