### ISSUE TITLE
Invoke_Pester_Tests_v4: Fails when using PesterScript with a hashtable

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#303]
When using parameter `PesterScript` together with a hashtable the following fails:

https://github.com/gaelcolas/Sampler/blob/a8cd70812fb4af5710c19f97d608cc59047ff6fd/.build/tasks/Invoke-Pester.pester.build.ps1#L310

It should be `Convert-SamplerHashtableToString` and not `Convert-HashtableToString`.

**Comment by gaelcolas** [comment]
@johlju can this one be closed?

**Comment by johlju** [comment]
Right. Forgot to auto close it with the PR.
