### ISSUE TITLE
Remove task `Set_Build_Environment_Variables`?

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#376]
The following file contains the task `Set_Build_Environment_Variables`:

https://github.com/gaelcolas/Sampler/blob/main/.build/tasks/Set-BuildEnvironment.BuildHelpers.build.ps1

There are no reference for any task or meta task using the task `Set_Build_Environment_Variables`. Can we remove it?

**Comment by johlju** [comment]
@gaelcolas you have any input on this?

**Comment by gaelcolas** [comment]
Build helpers is not used anymore, so I think all references and this file can be removed
