### ISSUE TITLE
A mistake in the psresourceget section of the README.md

### ISSUE THREAD

**Issue by fMichaleczek** [gaelcolas/Sampler#445]
There is a mistake in the _psresourceget_ section of the _README.md_ here : 

![image](https://github.com/gaelcolas/Sampler/assets/6187529/d048eaf8-7b87-4a63-98e7-6d52754c84b3)
[README#psresourceget](https://github.com/gaelcolas/Sampler#psresourceget)

**The expected command should be :**
```
.\build.ps1 -ResolveDependency -Tasks noop -UsePSResourceGet 
```

**Comment by johlju** [comment]
Ah,copy/paste mistake. Thanks for finding it and reporting it.
