### ISSUE TITLE
Why can't Sampler build Sampler?

### ISSUE THREAD

**Issue by DennisL68** [gaelcolas/Sampler#491]
When I build and package `Sampler` from a local clone using `build.ps1`, a lot of files are missing that are part of the packet of `Sampler` that I install from `PS Gallery`.

Doesn't "Eat your own dog food" apply for this project and in that case - shouldn't it?

**Comment by johlju** [comment]
I have no issues cloning this repo and running `./build.ps1` - that is done on each commit to this repo, as well to be able to run tests locally.

**Comment by DennisL68** [comment]
Ok, I was apparently somewhat confused when looking at this ;)

There's no issues.
