### ISSUE TITLE
Module (having classes and functions) built with sampler. Importing module, classes not visible.

### ISSUE THREAD

**Issue by KarstenHabay** [gaelcolas/Sampler#499]
Hi,

I'm building my modules with sampler. They contain mostly classes and functions. 

I got 2 major issues with my classes:
- When I want to use the module using Import-Module it all seems to work fine, except that my classes are not visible. When I try to instantiate a class I get: InvalidOperation: Unable to find type [myClassName].
- In my Pester tests, I force Import the module in a BeforeAll struct, pretty much like in the generated examples. Same result here: RuntimeException: Unable to find type [MyClassName].

Am I missing something? I couldn't find much info on using classes in the sampler help. Functions are exported through the Manifest. I was unable to find anything on classes. They are copied into my .psm1 file.

Any help would be greatly appreciated.

Greets,
Karsten

**Comment by johlju** [comment]
Great that you found it, it is normally added to prefix.ps1 and update build configuration to recognize that file.
