### ISSUE TITLE
Make sure FunctionToExport is not set to *

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Sampler#67]
Currently the template sets to * (which is convenient for dev private function but will cause issues). A test should ensure it's not set to * so that Module Builder can update it.

**Comment by NicolasBn** [comment]
In case of no functions are defining in the 'Public' folder, ModuleBuilder doesn't update the FunctionToExport key in the manifest.
See : https://github.com/PoshCode/ModuleBuilder/blob/abb0e09297d55e6c9e3f519b7e177eae1da7f3d9/Source/Public/Build-Module.ps1#L214

If private functions are present in the 'Private' folder, they will be exported with Import-Module :

![image](https://user-images.githubusercontent.com/25097989/95339195-1a1a5180-08b4-11eb-8c8f-dadb65e3a140.png)
