### ISSUE TITLE
QA: The test General module control

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#83]
This test verifies that the module can be imported

https://github.com/gaelcolas/Sampler/blob/0b6e68ada7a66fc01a212a13be7b0b8a6f9db04f/tests/QA/module.tests.ps1#L40-L43

But if the module cannot be imported the script will fail at the top, never running the above test

https://github.com/gaelcolas/Sampler/blob/0b6e68ada7a66fc01a212a13be7b0b8a6f9db04f/tests/QA/module.tests.ps1#L15-L16

Suggest that the test that imports the module does so in a `script` variable and reuse that for the other tests that verifies functions.

**Comment by gaelcolas** [comment]
Given that the unit tests are targeting the built module, can't we assume that is tested and just remove that test completly?

**Comment by johlju** [comment]
Yes agree to remove it.

**Comment by gaelcolas** [comment]
PR #88 should remove this file from the DSC Community template as per #84.

**Comment by gaelcolas** [comment]
This has been removed for the DSC Community Module Type.
