### ISSUE TITLE
Sampler: HQRM Tests are run twice for every DSC resource

### ISSUE THREAD

**Issue by danielboth** [gaelcolas/Sampler#90]
Currently, HQRM tests are run twice for DSC resource in a module. For example see this build result:

https://dev.azure.com/dsccommunity/xFailOverCluster/_build/results?buildId=383&view=logs&j=47266b63-9d03-5281-d38b-75133a4264f6&t=4d8b314c-6b76-5ae4-aed5-2779b7a3afdb&l=595
https://dev.azure.com/dsccommunity/xFailOverCluster/_build/results?buildId=383&view=logs&j=47266b63-9d03-5281-d38b-75133a4264f6&t=4d8b314c-6b76-5ae4-aed5-2779b7a3afdb&l=659

It lists all resources twice (which makes me assume the tests themselves are run twice as well). The same thing happens to me locally when running the HQRM tests on the xRemoteDesktopSessionHost module, so this is not an issue in just the CI setup.

**Comment by gaelcolas** [comment]
Actually, it's not running twice, but once on the source once on the Built module.
That is to help with localising (i.e. line number) where the issue comes from.
Fix the code once, resolves both issues.

**Comment by johlju** [comment]
We have an issue here that someone can work on that will resolve this; https://github.com/dsccommunity/DscResource.Test/issues/57

Closing this as HQRM tests are external to this module. I don't think we need to change Sampler to resolve the above issue.
