### ISSUE TITLE
Sampler.psm1 in generated using BOM in the output folder

### ISSUE THREAD

**Issue by johlju** [gaelcolas/Sampler#97]
When running the Sampler `build.ps1 -task build` the module is built but the `Sampler.psm1` file is built using `UTF-8 with BOM` which results in the BOM test failing locally.

This occurred on Windows 10 (Insider) with Windows PowerShell. 

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by johlju** [comment]
Tests failed with 

```
  Describing Common Tests - Validate Module Files

    Context Sampler.psm1
WARNING: Sampler.psm1 contain Byte Order Mark (BOM). Use fixer function 'ConvertTo-ASCII'.
      [-] Module file 'Sampler.psm1' should not have Byte Order Mark (BOM) 28ms
        Expected $false, but got $true.
        39:                 $moduleFileHasBom | Should -BeFalse
        at <ScriptBlock>, C:\source\Sampler\output\RequiredModules\DscResource.Test\0.11.1\Tests\QA\ModuleFiles.common.Tests.ps1: line 39
```

**Comment by tmeckel** [comment]
@johlju bumped on that error as well, when I tried to build the `Sampler` module, as requested in the PR regulations. Because the offending `Sampler.psm1` file is located in the output folder, I was wondering which component inside the build pipeline creates this file and I used `findstr` on the complete project folder but, at a first glance, I couldn't locate the culprit. Do you have any infos about this?

**Comment by gaelcolas** [comment]
The problem here is ModuleBuilder, and probably because we are pinning v1.0.0 for another reason.
If we build on linux, it will be UTF8 no-bom by default.
If you build on Windows PS, it will be UTF8 with bom.

Newer version of ModuleBuilder fixes that, but I don't think v2.0.0 is released yet.

**Comment by johlju** [comment]
A version of ModuleBuilder that fixes this has been release, and the latest version of this module have had a fix to work with the latest ModuleBuildet.

Closing this issue.

**Comment by raandree** [comment]
I have the same issue with ModuleBuilder 1.7.0 again with the simple repo https://github.com/raandree/Datum.InvokeCommand. Am I doing something wrong? The file 'Datum.InvokeCommand.psm1' does not exist in the repo and is created by the build job.

```
Executing script C:\Git\Datum.InvokeCommand\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\ModuleFiles.common.Tests.ps1

  Describing Common Tests - Validate Module Files

    Context Datum.InvokeCommand.psm1
WARNING: Datum.InvokeCommand.psm1 contain Byte Order Mark (BOM). Use fixer function 'ConvertTo-ASCII'.
      [-] Module file 'Datum.InvokeCommand.psm1' should not have Byte Order Mark (BOM) 46ms
        Expected $false, but got $true.
        39:                 $moduleFileHasBom | Should -BeFalse
        at <ScriptBlock>, C:\Git\Datum.InvokeCommand\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\ModuleFiles.common.Tests.ps1: line 39

Executing script C:\Git\Datum.InvokeCommand\output\RequiredModules\DscResource.Test\0.13.3\Tests\QA\ModuleManifest.common.Tests.ps1
```

**Comment by johlju** [comment]
Your repo looks good, the build.yml do have the UTF8 setting that was missing in one of the repos that got this error. I can look further when I’m at a computer.
